PRODUCT_PACKAGES += \
	IchnaeaNlpBackend \
	NominatimGeocoderBackend \
	UnifiedNlp \
	FDroidPrivilegedExtension \
	FDroid \
	AuroraServices \
	AuroraDroid \
	AuroraStore \
	HeyTap \
	TrichromeLibrary \
	SetEdit \
	FingerAds \
	TraccarClient \
	ZeroTierOne \
	AnyConnect \
	Davx5 \
	NextCloud \
	VLC \
	Bitwarden \
	GoogleAuthenticator \
	FirefoxBeta \
	OpenCamera \
	GhostCommander \
	GhostCommanderSMB \
	GhostCommanderWebDAV \
	RotationControl \
	FossifySMS \
	OsmAndPlus \
	ScreenshotTile \
	SimpleGalleryPro \
	additional_repos.xml
