PRODUCT_PACKAGES += \
	IchnaeaNlpBackend \
	NominatimGeocoderBackend \
	FDroid \
	FDroidPrivilegedExtension \
	UnifiedNlp \
	DroidGuard \
	AuroraServices \
	AuroraDroid \
	AuroraStore \
	BromiteSystemWebView \
	SetEdit \
	FingerAds \
	TraccarClient \
	BaiduInput \
	Bitwarden \
	Estrongs \
	FirefoxBeta \
	OpenCamera \
	GhostCommander \
	GhostCommanderSMB \
	GhostCommanderWebDAV \
	HMSCore \
	Lawnchair \
	QKSMS \
	OsmAndPlus \
	ScreenshotTile \
	SimpleGalleryPro \
	Snapseed \
	Wandoujia \
	LibreraReader \
	KOReader \
	GeometricWeather \
	Zulip \
	Weixin \
	QQ \
	QQPim \
	ZeroTierOne \
	Davx5 \
	additional_repos.xml
