PRODUCT_PACKAGES += \
	IchnaeaNlpBackend \
	NominatimGeocoderBackend \
	UnifiedNlp \
	FDroidPrivilegedExtension \
	FDroid \
	AuroraServices \
	AuroraDroid \
	AuroraStore \
	BromiteSystemWebView \
	SetEdit \
	FingerAds \
	TraccarClient \
	ZeroTierOne \
	WireGuard \
	Davx5 \
	NextCloud \
	VLC \
	Bitwarden \
	GoogleAuthenticator \
	FirefoxBeta \
	OpenCamera \
	GhostCommander \
	GhostCommanderSMB \
	GhostCommanderWebDAV \
	HMSCore \
	Lawnchair \
	RotationControl \
	QKSMS \
	OsmAndPlus \
	ScreenshotTile \
	SimpleGalleryPro \
	Snapseed \
	CoolApk \
	LibreraReader \
	fdroid_microg_repos.xml
